import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { api } from './api.js'
import GoalDeadlineNotice from './GoalDeadlineNotice.jsx'
import './styles.css'
import './planner.css'

const DAYS = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']
const DAY_NAMES = { MON: 'MONDAY', TUE: 'TUESDAY', WED: 'WEDNESDAY', THU: 'THURSDAY', FRI: 'FRIDAY', SAT: 'SATURDAY', SUN: 'SUNDAY' }
const KOREAN_DAYS = { MONDAY: '월', TUESDAY: '화', WEDNESDAY: '수', THURSDAY: '목', FRIDAY: '금', SATURDAY: '토', SUNDAY: '일' }
const emptyGoal = { title: '', focusArea: '', startDate: new Date().toISOString().slice(0, 10), targetDate: '', currentLevel: 'BEGINNER', dailyStudyHours: 2, breakMinutes: 10, availableDays: DAYS }
const hm = value => `${String(Math.floor(value / 2)).padStart(2, '0')}:${value % 2 ? '30' : '00'}`
const ranges = values => { const ordered = [...values].sort((a, b) => a - b); if (!ordered.length) return []; const result = []; let start = ordered[0], previous = start; ordered.slice(1).forEach(value => { if (value !== previous + 1) { result.push([start, previous + 1]); start = value }; previous = value }); result.push([start, previous + 1]); return result }

function AvailabilityClock({ selected, setSelected, disabled = false }) {
  const [period, setPeriod] = useState('PM'); const [paint, setPaint] = useState(null); const offset = period === 'AM' ? 0 : 24
  const toggle = index => setSelected(current => current.includes(index) ? current.filter(value => value !== index) : [...current, index].sort((a, b) => a - b))
  const down = (index, event) => { if (disabled) return; event.currentTarget.setPointerCapture(event.pointerId); setPaint({ erase: selected.includes(index), seen: new Set([index]) }); toggle(index) }
  const move = event => { if (!paint) return; const rect = event.currentTarget.getBoundingClientRect(); const x = (event.clientX - rect.left) * 320 / rect.width - 160; const y = (event.clientY - rect.top) * 320 / rect.height - 160; if (Math.hypot(x, y) > 104) return; const angle = (Math.atan2(y, x) + Math.PI / 2 + Math.PI * 2) % (Math.PI * 2); const index = offset + Math.floor(angle / (Math.PI * 2) * 24); if (paint.seen.has(index)) return; paint.seen.add(index); const active = selected.includes(index); if ((paint.erase && active) || (!paint.erase && !active)) toggle(index) }
  const sector = index => { const a = index / 24 * Math.PI * 2 - Math.PI / 2, b = (index + 1) / 24 * Math.PI * 2 - Math.PI / 2, r = 104; return `M160 160 L${160 + r * Math.cos(a)} ${160 + r * Math.sin(a)} A${r} ${r} 0 0 1 ${160 + r * Math.cos(b)} ${160 + r * Math.sin(b)} Z` }
  return <div className={`clock-panel ${disabled ? 'is-disabled' : ''}`}><div className="period-toggle"><button type="button" disabled={disabled} className={period === 'AM' ? 'active' : ''} onClick={() => setPeriod('AM')}>오전</button><button type="button" disabled={disabled} className={period === 'PM' ? 'active' : ''} onClick={() => setPeriod('PM')}>오후</button></div><svg className="analog-availability" viewBox="0 0 320 320" onPointerMove={move} onPointerUp={() => setPaint(null)} onPointerLeave={() => setPaint(null)}>{Array.from({ length: 24 }, (_, index) => <path key={index} d={sector(index)} className={selected.includes(offset + index) ? 'analog-sector active' : 'analog-sector'} onPointerDown={event => down(offset + index, event)} />)}{Array.from({ length: 12 }, (_, index) => { const angle = index / 12 * Math.PI * 2 - Math.PI / 2; return <text key={index} x={160 + 145 * Math.cos(angle)} y={165 + 145 * Math.sin(angle)} textAnchor="middle" className="analog-number">{index || 12}</text> })}</svg><strong className="clock-summary">선택됨: {ranges(selected).map(([start, end]) => `${hm(start)}–${hm(end)}`).join(', ') || '없음'}</strong></div>
}

function AuthScreen({ onAuthenticated }) {
  const [mode, setMode] = useState('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [nickname, setNickname] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const submit = async event => { event.preventDefault(); setBusy(true); setError(''); try { if (mode === 'signup') { await api.signup(email, password, nickname); setMode('login'); setPassword(''); setError('회원가입이 완료되었습니다. 로그인해주세요.'); return }; const result = await api.login(email, password); localStorage.setItem('steadyTeller.accessToken', result.accessToken); onAuthenticated() } catch (reason) { setError(reason.message) } finally { setBusy(false) } }
  return <main className="auth-shell"><section className="auth-card"><span>STEADY TELLER</span><h1>{mode === 'login' ? '다시 만나서 반가워요.' : '학습 계획을 시작해보세요.'}</h1><p>목표와 실제 가능한 시간을 기준으로 학습 일정을 만듭니다.</p><form onSubmit={submit}><label>이메일<input type="email" required value={email} onChange={event => setEmail(event.target.value)} /></label>{mode === 'signup' && <label>닉네임<input required value={nickname} onChange={event => setNickname(event.target.value)} /></label>}<label>비밀번호<input type="password" minLength="8" required value={password} onChange={event => setPassword(event.target.value)} /></label>{error && <p className="auth-message">{error}</p>}<button className="primary" disabled={busy}>{busy ? '처리중...' : mode === 'login' ? '로그인' : '회원가입'}</button></form><button type="button" className="auth-switch" onClick={() => { setMode(mode === 'login' ? 'signup' : 'login'); setError('') }}>{mode === 'login' ? '회원가입하기' : '로그인으로 돌아가기'}</button></section></main>
}

function App() {
  const [tab, setTab] = useState('dashboard'); const [goals, setGoals] = useState([]); const [goalId, setGoalId] = useState('')
  const [goalForm, setGoalForm] = useState(emptyGoal); const [windows, setWindows] = useState([]); const [day, setDay] = useState('MON'); const [slots, setSlots] = useState([])
  const [tasks, setTasks] = useState([]); const [schedule, setSchedule] = useState(null); const [statistics, setStatistics] = useState(null); const [notice, setNotice] = useState(''); const [isGenerating, setIsGenerating] = useState(false); const [authenticated, setAuthenticated] = useState(() => Boolean(localStorage.getItem('steadyTeller.accessToken')))
  const goal = useMemo(() => goals.find(item => item.id === Number(goalId)), [goals, goalId])
  const load = async requestedId => { const [goalList, savedWindows] = await Promise.all([api.goals(), api.availabilities()]); setGoals(goalList); setWindows(savedWindows); const id = requestedId ?? (goalId ? Number(goalId) : goalList[0]?.id); if (!id) { setTasks([]); setSchedule(null); return }; setGoalId(String(id)); const [confirmed, summaries] = await Promise.all([api.confirmedTasks(id), api.schedules(id)]); setTasks(confirmed); setSchedule(summaries[0] ? await api.schedule(summaries[0].scheduleId) : null) }
  useEffect(() => { if (authenticated) load().catch(error => setNotice(error.message)) }, [authenticated])
  useEffect(() => { if (goal) setGoalForm({ ...emptyGoal, ...goal }) }, [goal])
  const run = async (action, message) => { try { await action(); await load(goal?.id); setNotice(message) } catch (error) { setNotice(error.message) } }
  const addWindows = () => { const additions = ranges(slots).map(([start, end]) => ({ dayOfWeek: DAY_NAMES[day], startTime: hm(start), endTime: hm(end), enabled: true })); if (!additions.length) return setNotice('시계에서 가용시간을 선택해주세요.'); setWindows(current => [...current, ...additions]); setSlots([]) }
  const generatePlan = async event => { event.preventDefault(); if (isGenerating || !windows.length) return setNotice(windows.length ? '' : '최소 한 개의 가용시간을 등록해주세요.'); setIsGenerating(true); try { const result = await api.generateGoalPlan({ goal: { ...goalForm, availableDays: [...new Set(windows.filter(item => item.enabled).map(item => item.dayOfWeek.slice(0, 3)))], dailyStudyHours: Math.max(1, goalForm.dailyStudyHours) }, availabilities: windows.map(({ dayOfWeek, startTime, endTime, enabled }) => ({ dayOfWeek, startTime, endTime: endTime === '24:00' ? '23:59' : endTime, enabled })) }); setGoalId(String(result.goal.id)); await load(result.goal.id); setTab('dashboard'); setNotice('목표, 태스크, 시간대 기반 일정을 생성했습니다.') } catch (error) { setNotice(error.message) } finally { setIsGenerating(false) } }
  const loadStatistics = async () => { if (!goal) return setNotice('먼저 목표를 선택해주세요.'); try { const today = new Date().toISOString().slice(0, 10); const [summary, goalStats] = await Promise.all([api.statisticsSummary(goal.startDate, today), api.goalStatistics(goal.id)]); setStatistics({ ...summary, goalStats }) } catch (error) { setNotice(error.message) } }
  const pending = schedule?.dailySchedules.flatMap(daySchedule => daySchedule.items.map(item => ({ ...item, date: daySchedule.date }))) ?? []
  const tabs = [['dashboard', '대시보드'], ['plan', '목표·일정 생성'], ['progress', '일정 진행'], ['statistics', '통계']]
  if (!authenticated) return <AuthScreen onAuthenticated={() => setAuthenticated(true)} />
  return <div className="planner-shell"><header><b>SteadyTeller</b><div className="header-actions"><select value={goalId} onChange={event => load(Number(event.target.value))}><option value="">목표 선택</option>{goals.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select><button type="button" onClick={() => { localStorage.removeItem('steadyTeller.accessToken'); setAuthenticated(false); setGoals([]); setGoalId('') }}>로그아웃</button></div></header><main>{notice && <p className="notice">{notice}</p>}<nav className="app-tabs">{tabs.map(([id, label]) => <button type="button" key={id} className={tab === id ? 'active' : ''} onClick={() => { setTab(id); if (id === 'statistics') loadStatistics() }}>{label}</button>)}</nav>
    {tab === 'dashboard' && <section className="tab-content"><section className="planner-hero"><span>STUDY DASHBOARD</span><h1>{goal ? goal.title : '진행 중인 목표를 선택하세요.'}</h1><p>{goal ? `${goal.startDate} 시작 · ${goal.targetDate} 목표 완료` : '목표·일정 생성 탭에서 새 학습 계획을 만들 수 있습니다.'}</p></section>{goal && <><div className="metric-grid"><article><span>확정 태스크</span><strong>{tasks.length}</strong></article><article><span>완료 태스크</span><strong>{tasks.filter(item => item.status === 'FINISHED').length}</strong></article><article><span>남은 일정</span><strong>{pending.filter(item => item.kind === 'REGULAR' && item.status !== 'FINISHED').length}</strong></article></div><section className="panel"><h2>다음 학습</h2>{pending.find(item => item.kind === 'REGULAR' && item.status !== 'FINISHED') ? (() => { const item = pending.find(value => value.kind === 'REGULAR' && value.status !== 'FINISHED'); return <div className="next-task"><b>{item.date} · {item.startTime?.slice(0, 5)}–{item.endTime?.slice(0, 5)}</b><span>{item.title}</span><button onClick={() => run(() => api.startScheduleItem(schedule.scheduleId, item.scheduleItemId), '학습 타이머를 시작했습니다.')}>공부 시작</button></div> })() : <p className="muted">예정된 학습이 없습니다.</p>}</section><GoalDeadlineNotice goalId={goal.id} refreshToken={schedule?.scheduleId} onContinued={() => load(goal.id)} /></>}</section>}
    {tab === 'plan' && <section className="tab-content"><section className="planner-hero"><span>PLAN BUILDER</span><h1>목표와 가용시간으로 한 번에 일정을 만드세요.</h1><p>AI는 목표일까지의 실제 가용시간을 넘지 않도록 태스크 크기와 일정을 생성합니다.</p></section><form onSubmit={generatePlan}><fieldset className="plan-form-fieldset" disabled={isGenerating}><section className="panel"><h2>1. 목표 정보</h2><div className="goal-form"><label>목표<input required value={goalForm.title} onChange={event => setGoalForm({ ...goalForm, title: event.target.value })} /></label><label>집중 분야<input required value={goalForm.focusArea} onChange={event => setGoalForm({ ...goalForm, focusArea: event.target.value })} /></label><div className="form-pair"><label>시작일<input type="date" required value={goalForm.startDate} onChange={event => setGoalForm({ ...goalForm, startDate: event.target.value })} /></label><label>목표일<input type="date" required value={goalForm.targetDate} onChange={event => setGoalForm({ ...goalForm, targetDate: event.target.value })} /></label></div><label>태스크 사이 휴식(분)<input type="number" min="0" value={goalForm.breakMinutes} onChange={event => setGoalForm({ ...goalForm, breakMinutes: Number(event.target.value) })} /></label></div></section><section className="panel"><h2>2. 요일별 가용시간</h2><div className="weekday">{DAYS.map(value => <button type="button" key={value} className={day === value ? 'active' : ''} onClick={() => { setDay(value); setSlots([]) }}>{KOREAN_DAYS[DAY_NAMES[value]]}</button>)}</div><AvailabilityClock selected={slots} setSelected={setSlots} disabled={isGenerating} /><button type="button" className="primary availability-save" onClick={addWindows}>선택한 시간 추가</button><div className="availability-list"><h3>등록할 가용시간</h3>{windows.length ? windows.map((item, index) => <div className="row" key={`${item.dayOfWeek}-${item.startTime}-${index}`}><span>{KOREAN_DAYS[item.dayOfWeek]}요일 {item.startTime}–{item.endTime}</span><button type="button" onClick={() => setWindows(current => current.filter((_, value) => value !== index))}>삭제</button></div>) : <p className="muted">등록된 가용시간이 없습니다.</p>}</div></section><button className="primary generate-plan" disabled={isGenerating}>{isGenerating ? '생성중...' : '일정 생성'}</button></fieldset></form></section>}
    {tab === 'progress' && <section className="tab-content"><section className="planner-hero"><span>PLAN PROGRESS</span><h1>오늘의 일정과 보충 일정을 관리하세요.</h1></section>{schedule ? <><section className="panel">{schedule.dailySchedules.map(daySchedule => <div className="day" key={daySchedule.date}><b>{daySchedule.date}</b>{daySchedule.items.map(item => <div className={`row ${item.kind?.toLowerCase()}`} key={item.scheduleItemId}><span>{item.startTime?.slice(0, 5)}–{item.endTime?.slice(0, 5)} · {item.title}</span><small>{item.status}</small>{item.kind === 'REGULAR' && item.status !== 'FINISHED' && <div className="row-actions"><button onClick={() => run(() => api.startScheduleItem(schedule.scheduleId, item.scheduleItemId), '타이머를 시작했습니다.')}>시작</button><button onClick={() => run(() => api.completeScheduleItem(schedule.scheduleId, item.scheduleItemId), '완료 기록을 저장했습니다.')}>완료</button><button onClick={() => run(() => api.deferToSupplement(schedule.scheduleId, item.scheduleItemId), '보충시간으로 미뤘습니다.')}>보충시간으로</button><button onClick={() => run(() => api.failScheduleItem(schedule.scheduleId, item.scheduleItemId, { reasonCode: 'OTHER', action: 'DEFER_TO_SUPPLEMENT' }), '실패를 기록했습니다.')}>실패</button></div>}</div>)}</div>)}</section><button className="primary" onClick={() => run(() => api.replanRemaining(schedule.scheduleId), '미완료 태스크만 남은 일정에 재배치했습니다.')}>남은 일정 전체 재조정</button></> : <section className="panel"><p className="muted">생성된 일정이 없습니다.</p></section>}</section>}
    {tab === 'statistics' && <section className="tab-content"><section className="planner-hero"><span>LEARNING INSIGHTS</span><h1>학습 기록과 실패 패턴을 확인하세요.</h1></section><section className="panel"><button className="primary" onClick={loadStatistics}>통계 새로고침</button>{statistics ? <div className="stats-list">{Object.entries(statistics.goalStats ?? {}).map(([key, value]) => <div className="row" key={key}><span>{key}</span><strong>{typeof value === 'object' ? JSON.stringify(value) : String(value)}</strong></div>)}{Object.entries(statistics).filter(([key]) => key !== 'goalStats').map(([key, value]) => <div className="row" key={key}><span>{key}</span><strong>{typeof value === 'object' ? JSON.stringify(value) : String(value)}</strong></div>)}</div> : <p className="muted">목표를 선택한 뒤 통계를 불러오세요.</p>}</section></section>}
  </main></div>
}

createRoot(document.getElementById('root')).render(<App />)
